### ISSUE TITLE
Sample application does not work for me

### ISSUE THREAD

**Issue by jehof** [AppMetrics/Samples.V2#1]
Hi there,

I have rebuild your sample using docker images of influxdb (influxdb:latest) and grafana (grafana/grafana:latest), but grafana displays no metrics. I have no glue what does wrong.

My application reports metrics to console and to influxdb. At least to the console are metrics written, like

`# TIMESTAMP: 636495668394262998
# MEASUREMENT: [microref] exponentially-decaying
# TAGS:
server = ets
app = ExceptionTrackingService
env = development
mtype = timer
unit = none
unit_dur = ms
unit_rate = min
# FIELDS:
count.meter = 1615
rate1m = 137.010611851044
rate5m = 131.660766061273
rate15m = 103.296205209632
rate.mean = 142.300803693763
samples = 1028
last = 61.4889
count.hist = 1615
sum = 105182.4244
min = 0.0066
max = 326.0895
mean = 66.0367309426613
median = 53.1109
stddev = 47.3901699559207
p999 = 326.0895
p99 = 239.0355
p98 = 199.5723
p95 = 159.3965
p75 = 82.7965
--------------------------------------------------------------
# TIMESTAMP: 636495668394262998
# MEASUREMENT: [microref] sliding-window
# TAGS:
server = ets
app = ExceptionTrackingService
env = development
mtype = timer
unit = none
unit_dur = ms
unit_rate = min
# FIELDS:
count.meter = 1615
rate1m = 137.001728520277
rate5m = 130.420918558536
rate15m = 97.6601777810052
rate.mean = 142.349191853956
samples = 1028
last = 57.077
count.hist = 1615
sum = 91324.5808
min = 0.0047
max = 235.109
mean = 58.344960311284
median = 51.74465
stddev = 36.9079073582399
p999 = 234.7663331
p99 = 190.96853
p98 = 162.853484
p95 = 135.75162
p75 = 70.9386
--------------------------------------------------------------
# TIMESTAMP: 636495668394262998
# MEASUREMENT: [microref] uniform
# TAGS:
server = ets
app = ExceptionTrackingService
env = development
mtype = timer
unit = none
unit_dur = ms
unit_rate = min
# FIELDS:
count.meter = 1616
rate1m = 136.98601620732
rate5m = 131.656430073653
rate15m = 103.295229324218
rate.mean = 142.352659039739
samples = 1028
last = 85.9752
count.hist = 1616
sum = 114507.9
min = 0.004
max = 611.2182
mean = 70.5293918287938
median = 57.66645
stddev = 52.461263664573
p999 = 603.625889800001
p99 = 233.731029
p98 = 210.642062
p95 = 170.11837
p75 = 90.926225
--------------------------------------------------------------
`
and something gets posted to the influxdb and the size of the db keeps growing

`[httpd] 172.19.0.1 - - [22/Dec/2017:19:11:23 +0000] "POST /write?db=microref HTTP/1.1" 204 0 "-" "-" e689f644-e74b-11e7-80d1-000000000000 80904
[httpd] 172.19.0.1 - - [22/Dec/2017:19:11:23 +0000] "POST /write?db=microref HTTP/1.1" 204 0 "-" "-" e69aa9b4-e74b-11e7-80d2-000000000000 5675
[httpd] 172.19.0.1 - - [22/Dec/2017:19:11:33 +0000] "POST /write?db=microref HTTP/1.1" 204 0 "-" "-" eccc084c-e74b-11e7-80d3-000000000000 67284
[httpd] 172.19.0.1 - - [22/Dec/2017:19:11:34 +0000] "POST /write?db=microref HTTP/1.1" 204 0 "-" "-" ecf2a2fa-e74b-11e7-80d4-000000000000 10740
[httpd] 172.19.0.1 - - [22/Dec/2017:19:11:44 +0000] "POST /write?db=microref HTTP/1.1" 204 0 "-" "-" f2f515a1-e74b-11e7-80d5-000000000000 15245
[httpd] 172.19.0.1 - - [22/Dec/2017:19:11:44 +0000] "POST /write?db=microref HTTP/1.1" 204 0 "-" "-" f3145b89-e74b-11e7-80d6-000000000000 85370`

Grafane executes the following queries to InfluxDB, but it receives no results.

Request
`http://localhost:48086/query?db=microref&q=SELECT%20last(%22p95%22)%20AS%20%2295th%20percentile%22%2C%20last(%22p98%22)%20AS%20%2298th%20percentile%22%2C%20last(%22p99%22)%20AS%20%2299th%20percentile%22%2C%20median(%22median%22)%20AS%20%22median%22%20FROM%20%22application.httprequests__put_size%22%20WHERE%20(%22app%22%20%3D~%20%2F%5EExceptionTrackingService%24%2F%20AND%20%22env%22%20%3D~%20%2F%5Edevelopment%24%2F%20AND%20%22server%22%20%3D~%20%2F%5E(ets)%24%2F)%20AND%20time%20%3E%3D%20now()%20-%205m%20GROUP%20BY%20time(5s)%20fill(null)&epoch=ms`

Response
`{"results":[{"statement_id":0}]}`

So what I am doing wrong here? I would be glad if you could help me. If you need further information let me know.

Thanks in advance.

**Comment by jehof** [comment]
I´m using the following docker-compose files. I have enabled Docker Support to the project via Visual Studio 

docker-compose.yml
```
version: '3.2'

services:
  aspnetcore2.api.reservoirs:
    image: aspnetcore2.api.reservoirs
    build:
      context: .
      dockerfile: AspNetCore2.Api.Reservoirs/Dockerfile
  influxdb:
    image: influxdb:latest
```
docker-compose.override.yml
```
version: '3.2'

services:
  aspnetcore2.api.reservoirs:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "40800:80"
  influxdb:
    environment:
      - INFLUXDB_DB=test
    ports:
      - "48086:8086"
    container_name: "influxdb"
    hostname: "influxdb"
    volumes:
      - type: volume
        source: C:\docker\data\influxdb
        target: /var/lib/influxdb
```
